start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	Greater.c	-o	greater
run:
	./greater	${ARGS}	
clear:
	rm	greater
usage:
	@echo	"1)make build \n 2) make ARGS=Directory  \n 3)make clear"
