start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	fadd.c	-o	fadd
run:
	./fadd	${ARGS}	${ARGS2}
clear:
	rm	fadd
usage:
	@echo	"1)make build \n 2) make ARGS=file ARGS2=offeset run  \n 3)make clear"
 
 
