start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	rmdta.c	-o	trunc
run:
	./trunc	${ARGS}	${ARGS2}
clear:
	rm	trunc
usage:
	@echo	"1)make build \n 2) make ARGS=File ARGS2=Offset  \n 3)make clear"
