start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	Delete100.c	-o	del100
run:
	./del100	${ARGS}	
clear:
	rm	del100
usage:
	@echo	"1)make build \n 2) make ARGS=Directory   \n 3)make clear"
