start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	Create.c	-o	create
run:
	./create	${ARGS}	${ARGS2}
clear:
	rm	create
usage:
	@echo	"1)make build \n 2) make ARGS=Directory ARGS2=Filename  \n 3)make clear"
