start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	IO_REDIRECTION.c	-o	red
run:
	./red	${ARGS}	${W}
clear:
	rm	red
usage:
	@echo	"1)make build \n 2) make ARGS=ac|ca W=File_name run \n 3)make clear"
