start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	isequal.c	-o	isequal
run:
	./isequal	${ARGS}	${ARGS2}
clear:
	rm	isequal
usage:
	@echo	"1)make build \n 2) make ARGS=file1 ARGS2=file2 run  \n 3)make clear"
 
