start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	mkdir.c	-o	mkdir
run:
	./mkdir	${ARGS}
clear:
	rm	mkdir
usage:
	@echo	"1)make build \n 2) make ARGS=directory run \n 3)make clear"
