start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	wrfile.c	-o	wrf
run:
	./wrf	${ARGS}	${ARGS2}
clear:
	rm	wrf
usage:
	@echo	"1)make build \n 2) make ARGS=directory ARGS2=filewithdir run  \n 3)make clear"
