start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	CopyFiles.c	-o	cpyfl
run:
	./cpyfl	${ARGS}	${ARGS2}	
clear:
	rm	cpyfl
usage:
	@echo	"1)make build \n 2) make ARGS=Directory to copyfrom ARGS2=Directory to copy to   \n 3)make clear"
