start:
	@echo	"commands are 1)build 2)run 3)clear 4)usage"
build:
	gcc	oneforall.c	-o	ofa
run:
	./ofa	${ARGS}	
clear:
	rm	ofa
usage:
	@echo	"1)make build \n 2) make ARGS=directory run  \n 3)make clear"


